//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DK.Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public int StudentID { get; set; }
        public System.DateTime DOB { get; set; }
        public string ChucVu { get; set; }
        public string DonViCongTac { get; set; }
        public string QueQuan { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string XepLoai { get; set; }
        public Nullable<System.DateTime> NgayKi { get; set; }
        public string NguoiKi { get; set; }
        public Nullable<int> SoHieu { get; set; }
        public Nullable<int> SoVaoSo { get; set; }
        public int ClassID { get; set; }
        public bool Deleted { get; set; }
        public string FullName { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
    }
}
