//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DK.Framework.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [System.ComponentModel.DataAnnotations.Schema.Table("fwConfig")]
    public partial class fwConfig
    {
        [Key]
        public int ID { get; set; }
        public string Key { get; set; }
        public string Title { get; set; }
        public string Value { get; set; }
        public string Des { get; set; }
        public string Type { get; set; }
        public string DataForType { get; set; }
        public string Area { get; set; }
    }
}
