//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DK.Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Certificate = new HashSet<Certificate>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NguyenQuan { get; set; }
        public string TruQuan { get; set; }
        public string CapBac { get; set; }
        public string NgayNhapNgu { get; set; }
        public string ChucVu { get; set; }
        public string DonVi { get; set; }
        public string NgayVaoDang { get; set; }
        public string QuaTruong { get; set; }
        public string TrinhDoVanHoa { get; set; }
        public string SucKhoe { get; set; }
        public string GiaDinh { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public string ThanhPhanGiaDinh { get; set; }
        public string SDT { get; set; }
        public string SDTGiaDinh { get; set; }
        public string GhiChu { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime BirthDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certificate> Certificate { get; set; }
    }
}
