//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DK.Services.Models
{
    using System;
    using System.Collections.Generic;
    [System.ComponentModel.DataAnnotations.Schema.Table("StudentClass")]
    public partial class StudentClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentClass()
        {
            this.StudentClassSubject = new HashSet<StudentClassSubject>();
        }
    
        public int ID { get; set; }
        public int ClassID { get; set; }
        public int StudentID { get; set; }
        public Nullable<double> TBKT { get; set; }
        public string HocLuc { get; set; }
        public string RenLuyen { get; set; }
        public Nullable<double> KyChienThuat { get; set; }
        public Nullable<double> CTD { get; set; }
        public Nullable<double> DieuLenh { get; set; }
        public Nullable<double> DiemTrungBinh { get; set; }
        public string XepLoaiTotNghiep { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClassSubject> StudentClassSubject { get; set; }
    }
}
