//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DK.Services.Models
{
    using System;
    using System.Collections.Generic;
    [System.ComponentModel.DataAnnotations.Schema.Table("StudentClassSubject")]
    public partial class StudentClassSubject
    {
        public int ID { get; set; }
        public Nullable<int> StudentClassID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<double> Point { get; set; }
    
        public virtual StudentClass StudentClass { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
