//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DK.Services.Models
{
    using System;
    using System.Collections.Generic;
    [System.ComponentModel.DataAnnotations.Schema.Table("TimeLine")]
    public partial class TimeLine
    {
        public int ID { get; set; }
        public int ClassID { get; set; }
        public System.DateTime Date { get; set; }
        public string NoiDung { get; set; }
        public string ThoiGian { get; set; }
        public string NguoiPhuTrach { get; set; }
        public string GiaoVien { get; set; }
        public string DiaDiem { get; set; }
        public string VatChat { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
